# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Resnate' do
    pod 'libPusher', '1.6.1'
end

target 'ResnateTests' do

end

