# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
workspace ‘Resnate’
target 'Resnate' do
    pod 'libPusher', '1.6.1'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
end

target 'ResnateTests' do

end

